//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouchSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A1 {
            get {
                object obj = ResourceManager.GetObject("A1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A2 {
            get {
                object obj = ResourceManager.GetObject("A2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A3 {
            get {
                object obj = ResourceManager.GetObject("A3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A4 {
            get {
                object obj = ResourceManager.GetObject("A4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A5 {
            get {
                object obj = ResourceManager.GetObject("A5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A区1楼 {
            get {
                object obj = ResourceManager.GetObject("A区1楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A区2楼 {
            get {
                object obj = ResourceManager.GetObject("A区2楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A区3楼 {
            get {
                object obj = ResourceManager.GetObject("A区3楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A区4楼 {
            get {
                object obj = ResourceManager.GetObject("A区4楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap A区5楼 {
            get {
                object obj = ResourceManager.GetObject("A区5楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B1 {
            get {
                object obj = ResourceManager.GetObject("B1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B2 {
            get {
                object obj = ResourceManager.GetObject("B2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B3 {
            get {
                object obj = ResourceManager.GetObject("B3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B4 {
            get {
                object obj = ResourceManager.GetObject("B4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B5 {
            get {
                object obj = ResourceManager.GetObject("B5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Bg {
            get {
                object obj = ResourceManager.GetObject("Bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BgFocus {
            get {
                object obj = ResourceManager.GetObject("BgFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B区1楼 {
            get {
                object obj = ResourceManager.GetObject("B区1楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B区2楼 {
            get {
                object obj = ResourceManager.GetObject("B区2楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B区3楼 {
            get {
                object obj = ResourceManager.GetObject("B区3楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B区4楼 {
            get {
                object obj = ResourceManager.GetObject("B区4楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap B区5楼 {
            get {
                object obj = ResourceManager.GetObject("B区5楼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NewLCFB {
            get {
                object obj = ResourceManager.GetObject("NewLCFB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NewShouYe {
            get {
                object obj = ResourceManager.GetObject("NewShouYe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap New师资队伍 {
            get {
                object obj = ResourceManager.GetObject("New师资队伍", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap New校友捐赠 {
            get {
                object obj = ResourceManager.GetObject("New校友捐赠", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZhiMingPage1 {
            get {
                object obj = ResourceManager.GetObject("ZhiMingPage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZhiMingPage2 {
            get {
                object obj = ResourceManager.GetObject("ZhiMingPage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 专家 {
            get {
                object obj = ResourceManager.GetObject("专家", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 专家_副本 {
            get {
                object obj = ResourceManager.GetObject("专家_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 专家1 {
            get {
                object obj = ResourceManager.GetObject("专家1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 人才 {
            get {
                object obj = ResourceManager.GetObject("人才", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 人才_副本 {
            get {
                object obj = ResourceManager.GetObject("人才_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 人才1 {
            get {
                object obj = ResourceManager.GetObject("人才1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 创新团队背景 {
            get {
                object obj = ResourceManager.GetObject("创新团队背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革 {
            get {
                object obj = ResourceManager.GetObject("历史沿革", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革_副本 {
            get {
                object obj = ResourceManager.GetObject("历史沿革_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革1 {
            get {
                object obj = ResourceManager.GetObject("历史沿革1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革11 {
            get {
                object obj = ResourceManager.GetObject("历史沿革11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革2 {
            get {
                object obj = ResourceManager.GetObject("历史沿革2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革3 {
            get {
                object obj = ResourceManager.GetObject("历史沿革3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革4 {
            get {
                object obj = ResourceManager.GetObject("历史沿革4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革5 {
            get {
                object obj = ResourceManager.GetObject("历史沿革5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革6 {
            get {
                object obj = ResourceManager.GetObject("历史沿革6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革表 {
            get {
                object obj = ResourceManager.GetObject("历史沿革表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 历史沿革透明 {
            get {
                object obj = ResourceManager.GetObject("历史沿革透明", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 名师 {
            get {
                object obj = ResourceManager.GetObject("名师", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 名师_副本 {
            get {
                object obj = ResourceManager.GetObject("名师_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 名师1 {
            get {
                object obj = ResourceManager.GetObject("名师1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学校概况 {
            get {
                object obj = ResourceManager.GetObject("学校概况", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学校概况_副本 {
            get {
                object obj = ResourceManager.GetObject("学校概况_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学校简介 {
            get {
                object obj = ResourceManager.GetObject("学校简介", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学校简介_副本 {
            get {
                object obj = ResourceManager.GetObject("学校简介_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学校简介1 {
            get {
                object obj = ResourceManager.GetObject("学校简介1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学校领导 {
            get {
                object obj = ResourceManager.GetObject("学校领导", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学校领导_副本 {
            get {
                object obj = ResourceManager.GetObject("学校领导_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学校领导背景 {
            get {
                object obj = ResourceManager.GetObject("学校领导背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学者 {
            get {
                object obj = ResourceManager.GetObject("学者", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学者_副本 {
            get {
                object obj = ResourceManager.GetObject("学者_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学者1 {
            get {
                object obj = ResourceManager.GetObject("学者1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学院设置_返回 {
            get {
                object obj = ResourceManager.GetObject("学院设置-返回", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 学院设置_返回_副本 {
            get {
                object obj = ResourceManager.GetObject("学院设置-返回_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 师资概况_返回 {
            get {
                object obj = ResourceManager.GetObject("师资概况-返回", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 师资概况_返回副本 {
            get {
                object obj = ResourceManager.GetObject("师资概况-返回副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 师资概况_返回副本1 {
            get {
                object obj = ResourceManager.GetObject("师资概况-返回副本1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 师资概况背景 {
            get {
                object obj = ResourceManager.GetObject("师资概况背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 师资队伍 {
            get {
                object obj = ResourceManager.GetObject("师资队伍", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 师资队伍_副本 {
            get {
                object obj = ResourceManager.GetObject("师资队伍_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 师资队伍背景1 {
            get {
                object obj = ResourceManager.GetObject("师资队伍背景1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 杰出人才背景 {
            get {
                object obj = ResourceManager.GetObject("杰出人才背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校友之家 {
            get {
                object obj = ResourceManager.GetObject("校友之家", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校友之家_副本 {
            get {
                object obj = ResourceManager.GetObject("校友之家_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校友之家1 {
            get {
                object obj = ResourceManager.GetObject("校友之家1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校园简介背景设计 {
            get {
                object obj = ResourceManager.GetObject("校园简介背景设计", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校园规划 {
            get {
                object obj = ResourceManager.GetObject("校园规划", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校园规划_ {
            get {
                object obj = ResourceManager.GetObject("校园规划_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校园风光 {
            get {
                object obj = ResourceManager.GetObject("校园风光", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校园风光_副本 {
            get {
                object obj = ResourceManager.GetObject("校园风光_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校园风光1 {
            get {
                object obj = ResourceManager.GetObject("校园风光1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 校园风光2 {
            get {
                object obj = ResourceManager.GetObject("校园风光2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 楼层分布 {
            get {
                object obj = ResourceManager.GetObject("楼层分布", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 楼层分布_副本 {
            get {
                object obj = ResourceManager.GetObject("楼层分布_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 楼层分布1 {
            get {
                object obj = ResourceManager.GetObject("楼层分布1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 知名校友 {
            get {
                object obj = ResourceManager.GetObject("知名校友", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 组织机构 {
            get {
                object obj = ResourceManager.GetObject("组织机构", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 组织机构_副本 {
            get {
                object obj = ResourceManager.GetObject("组织机构_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 组织结构 {
            get {
                object obj = ResourceManager.GetObject("组织结构", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 组织结构1 {
            get {
                object obj = ResourceManager.GetObject("组织结构1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 组织结构2 {
            get {
                object obj = ResourceManager.GetObject("组织结构2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 蓝色首页 {
            get {
                object obj = ResourceManager.GetObject("蓝色首页", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 返回 {
            get {
                object obj = ResourceManager.GetObject("返回", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 返回_副本 {
            get {
                object obj = ResourceManager.GetObject("返回_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 院系设置 {
            get {
                object obj = ResourceManager.GetObject("院系设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 院系设置_副本 {
            get {
                object obj = ResourceManager.GetObject("院系设置_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 首页背景 {
            get {
                object obj = ResourceManager.GetObject("首页背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 首页背景1 {
            get {
                object obj = ResourceManager.GetObject("首页背景1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 首页背景11 {
            get {
                object obj = ResourceManager.GetObject("首页背景11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
